platform:
  #- x86
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
     - 
       job_name: Visual Studio 2019
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019


for:
# Visual studio
  - matrix:
      only:
        - job_name: Visual Studio 2019
    clone_folder: c:/projects/openimageviewer
    init:
      - cmd: |- 
          set arch=
          echo Platform is %PLATFORM%
          echo %arch%
          echo %APPVEYOR_BUILD_WORKER_IMAGE%
          if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
          if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set cmake_architecture=%PLATFORM%)
           
          echo %generator%

    before_build:
      - cmd: |-
          c:
          cd c:/projects/openimageviewer
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake --version
          cmake .. -G "Visual Studio 16 2019" -A %cmake_architecture%

    build:
      project: c:/projects/openimageviewer/build/openimageviewer.sln
      verbosity: minimal
      parallel: true
